
return {
    [1] = { type = "rod", id = 1, planner_name = "fuelRodUranium", item_name = "gregtech:gt.reactorUraniumSimple" },
    [2] = { type = "rod", id = 2, planner_name = "dualFuelRodUranium", item_name = "gregtech:gt.reactorUraniumDual" },
    [3] = { type = "rod", id = 3, planner_name = "quadFuelRodUranium", item_name = "gregtech:gt.reactorUraniumQuad" },
    [4] = { type = "rod", id = 4, planner_name = "fuelRodMox", item_name = "gregtech:gt.reactorMOXSimple" },
    [5] = { type = "rod", id = 5, planner_name = "dualFuelRodMox", item_name = "gregtech:gt.reactorMOXDual" },
    [6] = { type = "rod", id = 6, planner_name = "quadFuelRodMox", item_name = "gregtech:gt.reactorMOXQuad" },
    [7] = { type = "infra", id = 7, planner_name = "neutronReflector", item_name = "IC2:reactorReflector" },
    [8] = { type = "infra", id = 8, planner_name = "thickNeutronReflector", item_name = "IC2:reactorReflectorThick" },
    [9] = { type = "vent", id = 9, planner_name = "heatVent", item_name = "IC2:reactorVent" },
    [10] = { type = "vent", id = 10, planner_name = "advancedHeatVent", item_name = "IC2:reactorVentDiamond", automationThreshold = 900 },
    [11] = { type = "vent", id = 11, planner_name = "reactorHeatVent", item_name = "IC2:reactorVentCore", automationThreshold = 900 },
    [12] = { type = "vent", id = 12, planner_name = "componentHeatVent", item_name = "IC2:reactorVentSpread" },
    [13] = { type = "vent", id = 13, planner_name = "overclockedHeatVent", item_name = "IC2:reactorVentGold", automationThreshold = 900 },
    [14] = { type = "coolant", id = 14, planner_name = "coolantCell10k", item_name = "IC2:reactorCoolantSimple", automationThreshold = 9000 },
    [15] = { type = "coolant", id = 15, planner_name = "coolantCell30k", item_name = "IC2:reactorCoolantTriple", automationThreshold = 27000 },
    [16] = { type = "coolant", id = 16, planner_name = "coolantCell60k", item_name = "IC2:reactorCoolantSix", automationThreshold = 54000 },
    [17] = { type = "infra", id = 17, planner_name = "heatExchanger", item_name = "IC2:reactorHeatSwitch", automationThreshold = 2250 },
    [18] = { type = "infra", id = 18, planner_name = "advancedHeatExchanger", item_name = "IC2:reactorHeatSwitchDiamond", automationThreshold = 9000 },
    [19] = { type = "infra", id = 19, planner_name = "coreHeatExchanger", item_name = "IC2:reactorHeatSwitchCore", automationThreshold = 4500 },
    [20] = { type = "infra", id = 20, planner_name = "componentHeatExchanger", item_name = "IC2:reactorHeatSwitchSpread", automationThreshold = 4500 },
    [21] = { type = "infra", id = 21, planner_name = "reactorPlating", item_name = "IC2:reactorPlating" },
    [22] = { type = "infra", id = 22, planner_name = "heatCapacityReactorPlating", item_name = "IC2:reactorPlatingHeat" },
    [23] = { type = "infra", id = 23, planner_name = "containmentReactorPlating", item_name = "IC2:reactorPlatingExplosive" },
    [24] = { type = "coolant", id = 24, planner_name = "rshCondensator", item_name = "IC2:reactorCondensator", automationThreshold = 18000 },
    [25] = { type = "coolant", id = 25, planner_name = "lzhCondensator", item_name = "IC2:reactorCondensatorLap", automationThreshold = 90000 },
    [26] = { type = "rod", id = 26, planner_name = "fuelRodThorium", item_name = "gregtech:gt.Thoriumcell" },
    [27] = { type = "rod", id = 27, planner_name = "dualFuelRodThorium", item_name = "gregtech:gt.Double_Thoriumcell" },
    [28] = { type = "rod", id = 28, planner_name = "quadFuelRodThorium", item_name = "gregtech:gt.Quad_Thoriumcell" },
    [29] = { type = "coolant", id = 29, planner_name = "coolantCellHelium60k", item_name = "gregtech:gt.60k_Helium_Coolantcell", automationThreshold = 54000 },
    [30] = { type = "coolant", id = 30, planner_name = "coolantCellHelium180k", item_name = "gregtech:gt.180k_Helium_Coolantcell", automationThreshold = 162000 },
    [31] = { type = "coolant", id = 31, planner_name = "coolantCellHelium360k", item_name = "gregtech:gt.360k_Helium_Coolantcell", automationThreshold = 324000 },
    [32] = { type = "coolant", id = 32, planner_name = "coolantCellNak60k", item_name = "gregtech:gt.60k_NaK_Coolantcell", automationThreshold = 54000 },
    [33] = { type = "coolant", id = 33, planner_name = "coolantCellNak180k", item_name = "gregtech:gt.180k_NaK_Coolantcell", automationThreshold = 162000 },
    [34] = { type = "coolant", id = 34, planner_name = "coolantCellNak360k", item_name = "gregtech:gt.360k_NaK_Coolantcell", automationThreshold = 324000 },
    [35] = { type = "infra", id = 35, planner_name = "iridiumNeutronReflector", item_name = "gregtech:gt.neutronreflector" },
    -- Not in GT
    -- [36] = { type = "rod", id = 36, planner_name = "fuelRodNaquadah", item_name = "" },
    -- [37] = { type = "rod", id = 37, planner_name = "dualFuelRodNaquadah", item_name = "" },
    -- [38] = { type = "rod", id = 38, planner_name = "quadFuelRodNaquadah", item_name = "" },
    -- [39] = { type = "rod", id = 39, planner_name = "fuelRodCoaxium", item_name = "" },
    -- [40] = { type = "rod", id = 40, planner_name = "dualFuelRodCoaxium", item_name = "" },
    -- [41] = { type = "rod", id = 41, planner_name = "quadFuelRodCoaxium", item_name = "" },
    -- [42] = { type = "rod", id = 42, planner_name = "fuelRodCesium", item_name = "" },
    -- [43] = { type = "rod", id = 43, planner_name = "dualFuelRodCesium", item_name = "" },
    -- [44] = { type = "rod", id = 44, planner_name = "quadFuelRodCesium", item_name = "" },
    [45] = { type = "rod", id = 45, planner_name = "fuelRodNaquadahGTNH", item_name = "gregtech:gt.Naquadahcell" },
    [46] = { type = "rod", id = 46, planner_name = "dualFuelRodNaquadahGTNH", item_name = "gregtech:gt.Double_Naquadahcell" },
    [47] = { type = "rod", id = 47, planner_name = "quadFuelRodNaquadahGTNH", item_name = "gregtech:gt.Quad_Naquadahcell" },
    [48] = { type = "rod", id = 48, planner_name = "fuelRodNaquadria", item_name = "gregtech:gt.MNqCell" },
    [49] = { type = "rod", id = 49, planner_name = "dualFuelRodNaquadria", item_name = "gregtech:gt.Double_MNqCell" },
    [50] = { type = "rod", id = 50, planner_name = "quadFuelRodNaquadria", item_name = "gregtech:gt.Quad_MNqCell" },
    [51] = { type = "rod", id = 51, planner_name = "fuelRodTiberium", item_name = "gregtech:gt.Tiberiumcell" },
    [52] = { type = "rod", id = 52, planner_name = "dualFuelRodTiberium", item_name = "gregtech:gt.Double_Tiberiumcell" },
    [53] = { type = "rod", id = 53, planner_name = "quadFuelRodTiberium", item_name = "gregtech:gt.Quad_Tiberiumcell" },
    [54] = { type = "rod", id = 54, planner_name = "fuelRodTheCore", item_name = "bartworks:gt.Core_Reactor_Cell" },
    [55] = { type = "coolant", id = 55, planner_name = "coolantCellSpace180k", item_name = "gregtech:gt.180k_Space_Coolantcell", automationThreshold = 162000 },
    [56] = { type = "coolant", id = 56, planner_name = "coolantCellSpace360k", item_name = "gregtech:gt.360k_Space_Coolantcell", automationThreshold = 324000 },
    [57] = { type = "coolant", id = 57, planner_name = "coolantCellSpace540k", item_name = "gregtech:gt.540k_Space_Coolantcell", automationThreshold = 486000 },
    [58] = { type = "coolant", id = 58, planner_name = "coolantCellSpace1080k", item_name = "gregtech:gt.1080k_Space_Coolantcell", automationThreshold = 972000 },
    [59] = { type = "coolant", id = 59, planner_name = "coolantCellNeutronium1G", item_name = "gregtech:gt.neutroniumHeatCapacitor", automationThreshold = 900000000 },
    [60] = { type = "rod", id = 60, planner_name = "fuelRodCompressedUranium", item_name = "GoodGenerator:rodCompressedUranium" },
    [61] = { type = "rod", id = 61, planner_name = "dualFuelRodCompressedUranium", item_name = "GoodGenerator:rodCompressedUranium2" },
    [62] = { type = "rod", id = 62, planner_name = "quadFuelRodCompressedUranium", item_name = "GoodGenerator:rodCompressedUranium4" },
    [63] = { type = "rod", id = 63, planner_name = "fuelRodCompressedPlutonium", item_name = "GoodGenerator:rodCompressedPlutonium" },
    [64] = { type = "rod", id = 64, planner_name = "dualFuelRodCompressedPlutonium", item_name = "GoodGenerator:rodCompressedPlutonium2" },
    [65] = { type = "rod", id = 65, planner_name = "quadFuelRodCompressedPlutonium", item_name = "GoodGenerator:rodCompressedPlutonium4" },
    [66] = { type = "rod", id = 66, planner_name = "fuelRodLiquidUranium", item_name = "GoodGenerator:rodLiquidUranium" },
    [67] = { type = "rod", id = 67, planner_name = "dualFuelRodLiquidUranium", item_name = "GoodGenerator:rodLiquidUranium2" },
    [68] = { type = "rod", id = 68, planner_name = "quadFuelRodLiquidUranium", item_name = "GoodGenerator:rodLiquidUranium4" },
    [69] = { type = "rod", id = 69, planner_name = "fuelRodLiquidPlutonium", item_name = "GoodGenerator:rodLiquidPlutonium" },
    [70] = { type = "rod", id = 70, planner_name = "dualFuelRodLiquidPlutonium", item_name = "GoodGenerator:rodLiquidPlutonium2" },
    [71] = { type = "rod", id = 71, planner_name = "quadFuelRodLiquidPlutonium", item_name = "GoodGenerator:rodLiquidPlutonium4" },
    [72] = { type = "breeder", id = 72, planner_name = "fuelRodGlowstone", item_name = "gregtech:gt.glowstoneCell" },
}
